### ISSUE TITLE
Support for sorting?

### ISSUE THREAD

**Issue by patrickcate** [Desarol/drupal-jsonapi-client#18]
Does this library support [sorting](https://www.drupal.org/docs/core-modules-and-themes/core-modules/jsonapi-module/sorting) of results?

I didn't see anything in the examples or readme.

**Comment by Auspicus** [comment]
@patrickcate Hey! Sorry I didn't see this until just now. No, there's no support for sorting as of yet.

**Comment by Auspicus** [comment]
@patrickcate We do now support sorting :)
