### ISSUE TITLE
when doset this lib support Drupal9?

### ISSUE THREAD

**Issue by vangogogo** [Desarol/drupal-jsonapi-client#26]
Hi ，you really did a great job ,this package  make our work  easier than before,but I  wonder  when will this lib support Drupal9?

**Comment by Auspicus** [comment]
@vangogogo For the most part the JSON:API interface of Drupal 9 has stayed the same as Drupal 8 so this library should continue to work. If you'd like to create a ticket for any issues you run using this library with Drupal 9 then we'll be happy to take a look. Cheers! 🍻
